=== KalamaresFTW/XMLStuff/Modulo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Modulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nome" type="xs:string"/>
        <xs:element ref="Contidos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Contidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Bloque" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Bloque">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Titulo" type="xs:string"/>
        <xs:element name="Descricion" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="num" type="xs:string" use="required"/>
      <xs:attribute name="sesions" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KalamaresFTW/XMLStuff/Modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/pcostoubi/NetBeans%20Projects/Unidad2/Modulo.xsd">
  <Nome>Redes de Area Local</Nome>
  <Contidos>
    <Bloque sesions="60" num="1">
      <Titulo>Sistemas de Comunicanions</Titulo>
      <Descricion>Aspectos fisicos, protocolos e arquitecturas de redes</Descricion>
    </Bloque>
    <Bloque sesions="50" num="2">
      <Titulo>Redes de Datos</Titulo>
      <Descricion>Dispositivos de interconexion de redes locais e de area extensa</Descricion>
    </Bloque>
    <Bloque sesions="90" num="3">
      <Titulo>Redes de area local</Titulo>
      <Descricion>Administracion e xestion dunha rede de area local</Descricion>
    </Bloque>
    <Bloque sesions="60" num="4">
      <Titulo>Servizos Internet</Titulo>
      <Descricion>Adm. de servizos que empreguen protocolos estandar en Internet</Descricion>
    </Bloque>
  </Contidos>
</Modulo>
